### ISSUE TITLE
Интерфейс очень мелкий на экране айфона

### ISSUE THREAD

**Issue by alexander-ii** [zetx16/parking-lanes#5]
А может быть и на экранах других ретина-подобных устройств.
Если присмотреться, то и подложка тоже мелкая.

![img_3995](https://user-images.githubusercontent.com/25887642/34460480-e138237a-ee20-11e7-868a-3e0d87e52fb0.PNG)

**Comment by zetx16** [comment]
@alexander-ii, должно стать лучше

**Comment by alexander-ii** [comment]
Да, стало как надо. Но других устройств для проверки нету, потому не решаюсь закрыть задачку.
