### ISSUE TITLE
Some ways where parking lanes were added manually are not displayed

### ISSUE THREAD

**Issue by tohaklim** [zetx16/parking-lanes#8]
Not sure why this happens.
E.g. 
![image](https://user-images.githubusercontent.com/7071423/36351688-9fe7539a-14a5-11e8-9ecd-0fef31e5742f.png)
https://www.openstreetmap.org/edit?editor=id#map=18/53.71482/23.85540

**Comment by zetx16** [comment]
Need to add `parking:condition:<side>` tag

**Comment by tohaklim** [comment]
So, the viewer/editor will completely ignore these ways until tags are manually added?

**Comment by zetx16** [comment]
Understood, fixed, thanks you

**Comment by tohaklim** [comment]
Fixed, thanks!
